### ISSUE TITLE
Support YAML Inline Extend syntax

### ISSUE THREAD

**Issue by evilebottnawi** [ikatyang/yaml-unist-parser#273]
```yaml
foo:
 <<: &anchor
   K1: "One"
 K2: "Two"

bar:
 <<: *anchor
 K3: "Three"
```

Ref: https://github.com/prettier/prettier/issues/8876
