### ISSUE TITLE
Comment attach seems wired

### ISSUE THREAD

**Issue by fisker** [ikatyang/yaml-unist-parser#275]
In this, comment 1 is attached as `endComments`,

```yaml
- a
  # comment 1
- b
  # comment 2
```

When next one is longer, comment 1 is attached as `leadingComments`,
```yaml
- a
  # comment 1
- bb
  # comment 2
```

Same problem in `map`

```yaml
a:
  # comment 1
b:
  # comment 2
```

VS

```yaml
a:
  # comment 1
bb:
  # comment 2
```

Context: https://github.com/prettier/prettier/pull/9143#discussion_r484357690
